# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="vokela"

fpath=(/usr/local/share/zsh-completions $fpath)

DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(virtualenvwrapper virtualenv-prompt python pyenv zsh-autosuggestions)

if [ -f ~/.bash_profile ]; then
    source ~/.bash_profile
fi

source $ZSH/oh-my-zsh.sh
eval "$(rbenv init -)"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

if [ -f "$HOME/.zsh_aliases" ]; then
    source "$HOME/.zsh_aliases"
fi

if [ -f "$HOME/.zsh/bindkeys.zsh" ]; then
    source "$HOME/.zsh/bindkeys.zsh"
fi

if [ -f "$HOME/.zsh/functions.zsh" ]; then
    source "$HOME/.zsh/functions.zsh"
fi

alias zshreload=". ~/.zshrc"
